version: '3'

services:
    sciencebeam-pipelines:
        build:
            context: .
            dockerfile: Dockerfile
            args: 
                commit: ${IMAGE_TAG}
                version: ${VERSION}
        image: elifesciences/sciencebeam-pipelines:${IMAGE_TAG}
        command: ./server.sh \
            --host=0.0.0.0 --port=8075 \
            --grobid-url http://grobid:8070/api
        environment:
            - SCIENCEBEAM_DOC_CONVERT_PROCESS_TIMEOUT=${SCIENCEBEAM_DOC_CONVERT_PROCESS_TIMEOUT}
            - SCIENCEBEAM_CONSOLIDATE_HEADER=${SCIENCEBEAM_CONSOLIDATE_HEADER}
            - SCIENCEBEAM_CONSOLIDATE_CITATIONS=${SCIENCEBEAM_CONSOLIDATE_CITATIONS}
            - SCIENCEBEAM_INCLUDE_RAW_AFFILIATIONS=${SCIENCEBEAM_INCLUDE_RAW_AFFILIATIONS}
            - SCIENCEBEAM_INCLUDE_RAW_CITATIONS=${SCIENCEBEAM_INCLUDE_RAW_CITATIONS}
        ports:
            - "8075:8075"

    sciencebeam-pipelines-base-dev:
        build:
            context: .
            dockerfile: Dockerfile
            args: 
                commit: ${IMAGE_TAG}
                version: ${VERSION}
                install_dev: "y"
        image: elifesciences/sciencebeam-pipelines-base-dev:${IMAGE_TAG}

    sciencebeam-pipelines-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
            args: 
                base_image: elifesciences/sciencebeam-pipelines-base-dev:${IMAGE_TAG}
        image: elifesciences/sciencebeam-pipelines-dev:${IMAGE_TAG}
        depends_on:
            - sciencebeam-pipelines-base-dev

    grobid:
        image: lfoppiano/grobid:${GROBID_TAG}
        environment:
            - JAVA_OPTS=-Xmx1g
        ports:
            - "8070:8070"


    wait-for-it:
        image: willwill/wait-for-it
