version: '3'

# used by default but not in ci
services:
    sciencebeam-pipelines:
        depends_on:
            - grobid

    sciencebeam-pipelines-dev:
        volumes:
        - ./sciencebeam:/srv/sciencebeam-pipelines/sciencebeam
        - ./tests:/srv/sciencebeam-pipelines/tests
        - ./xslt:/srv/sciencebeam-pipelines/xslt
        environment:
            # avoid issues with .pyc/pyo files when mounting source directory
            PYTHONOPTIMIZE: ""
            PYTHONDONTWRITEBYTECODE: "1"
